### ISSUE TITLE
Exit code shown in the stage exception failure message is incorrect

### ISSUE THREAD

**Issue by Vahila** [mathworks/jenkins-matlab-plugin#258] opened 2023-10-12 18:33 UTC
In 2.10.1-SNAPSHOT-Qualification, the exit code shown in the message in a stage exception failure is incorrect.

I am using the following script:
exit(5)

In 2.10.0 MATLAB plugin(already released), the message shown is Received a nonzero exit code 1 while trying to run MATLAB
In 2.10.1, the message shown is Received a nonzero exit code 5 while trying to run MATLAB.

The same discrepancy is seen with below script as well

**Comment by sameagen-MW** [comment] 2023-10-13 14:28
This is an intended feature of the `run-matlab-command` binary. We're considering updating this as an enhancement in the future but for now it can be considered separately from the Jenkins plugin features.

**Comment by sameagen-MW** [comment] 2024-02-21 22:00
I'm going to go ahead and close this issue since it's a duplicate of one present on the `run-matlab-command` repo.

**Closed by sameagen-MW** 2024-02-21 22:00 UTC
