### ISSUE TITLE
"-sd" alone instead of "-sd matlab" results in a passing build

### ISSUE THREAD

**Issue by mw-hrastega** [mathworks/jenkins-matlab-plugin#293] opened 2024-02-16 20:27 UTC
I deleted "matlab" from the Startup Options box and ran a build with -sd alone as the startup option. I was expecting an incomplete option to result in a Jenkins build error; however, the build passed.

**Comment by sameagen-MW** [comment] 2024-02-16 20:34
<img width="718" alt="image" src="https://github.com/mathworks/jenkins-matlab-plugin/assets/122639681/4d2cfc97-22e2-439c-afac-e3903d33ebd5">

Here's a screenshot of how `matlab -batch` handles this case.

**Comment by sameagen-MW** [comment] 2024-02-16 20:36
I think that matching the behavior of the `matlab` executable is probably my preference, but I would be open to potentially changing the behavior if that ends up being the group consensus.

**Comment by mw-hrastega** [comment] 2024-02-16 20:37
> <img alt="image" width="718" src="https://private-user-images.githubusercontent.com/122639681/305551361-4d2cfc97-22e2-439c-afac-e3903d33ebd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMTYxMDUsIm5iZiI6MTcwODExNTgwNSwicGF0aCI6Ii8xMjI2Mzk2ODEvMzA1NTUxMzYxLTRkMmNmYzk3LTIyZTItNDM5Yy1hZmFjLWUzOTAzZDMzZWJkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQyMDM2NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2MzZTJhMmZkYWY5ODQ2OGM4M2UyYmY1NTA0MGYzNGVhNzQwNDc3NDFkNThkMmJmZjM1ZDQ5NzcyM2FmNjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C9L9vz5HyXndane-92cGNQeJXGMMeCPCsZ5GEeRlQBQ">
> Here's a screenshot of how `matlab -batch` handles this case.

Thanks @sameagen-MW for including a screenshot.

**Comment by sameagen-MW** [comment] 2024-02-20 13:57
Did the warning message show up in the Jenkins job Houman?

**Comment by mw-hrastega** [comment] 2024-02-20 14:23
> Did the warning message show up in the Jenkins job Houman?

Hmm. Not sure. Didn't inspect the build log 🤒

**Comment by Vahila** [comment] 2024-02-20 17:58
Hi, with the hpi file generated out of latest changes in 2.11.2  qual branch, I see weird behavior when just specifying -sd alone on Windows. Attaching screenshots for  reference.
Project run on Windows agent:
Console log:
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/f229bb8b-e2e1-469d-8d0b-e61e4a4a9c75)

Jenkins project config:
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/34142e68-0f41-4bf3-a71a-2f08cdbba9f5)
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/daeabaeb-9c5f-4094-a253-4941b93780e5)


And when project is run on Linux, I see some errors as below.
Console log:
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/cdb007b6-2de3-4bb5-a248-ba2d310c3798)
Jenkins Configure page:
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/5c7d600d-e039-42ff-b6eb-a45bc0b5fc8d)

**Comment by nbhoski** [comment] 2024-02-21 06:13
I tried it on command line and its exacttly the same behaviour as Jenkins 
<img width="571" alt="image" src="https://github.com/mathworks/jenkins-matlab-plugin/assets/47204011/141e7044-6609-45e1-9619-185f6c7168be">

@sameagen-MW is there any limitation from go lang exec that we are using ? since its not throwing any error on -sd

**Comment by sameagen-MW** [comment] 2024-02-21 21:52
Yep, after looking into it I can confirm that this is an issue with the way that `run-matlab-command` handles arguments. In this case what's happening is because we're appending `-batch "command"` after the flags, the full command would be `matlab -sd -batch "command"`, and it registers `-batch` as the argument for `-sd` leading to an error in parsing `"command"`.

I'll close the issue here and open an enhancement on `run-matlab-command`.

**Closed by sameagen-MW** 2024-02-21 21:52 UTC
Labels: question
