### ISSUE TITLE
MATLAB build results not reported as expected

### ISSUE THREAD

**Issue by mw-hrastega** [mathworks/jenkins-matlab-plugin#302] opened 2024-03-19 21:59 UTC
I ran a MATLAB build using the Jenkins plugin. Even though the build ran successfully, the MATLAB build results were not correctly reflected in the Jenkins interface.

Here is my build log followed by a screenshot of the reported build results:

Started by user [Houman Rastegarfar](http://localhost:8080/user/mw-hrastega)
Running as SYSTEM
Building in workspace C:\Users\hrastega\AppData\Local\Jenkins\.jenkins\workspace\myProject
Selected Git installation does not exist. Using Default
The recommended git tool is: NONE
No credentials specified
 > git.exe rev-parse --resolve-git-dir C:\Users\hrastega\AppData\Local\Jenkins\.jenkins\workspace\myProject\.git # timeout=10
Fetching changes from the remote Git repository
 > git.exe config remote.origin.url https://github.com/mw-hrastega/Times-Table-App.git # timeout=10
Fetching upstream changes from https://github.com/mw-hrastega/Times-Table-App.git
 > git.exe --version # timeout=10
 > git --version # 'git version 2.27.0.windows.1'
 > git.exe fetch --tags --force --progress -- https://github.com/mw-hrastega/Times-Table-App.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git.exe rev-parse "refs/remotes/origin/main^{commit}" # timeout=10
Checking out Revision b2381bc40b9ab8e1f010336e9cd9812579ebc8f4 (refs/remotes/origin/main)
 > git.exe config core.sparsecheckout # timeout=10
 > git.exe checkout -f b2381bc40b9ab8e1f010336e9cd9812579ebc8f4 # timeout=10
Commit message: "Update buildfile.m"
 > git.exe rev-list --no-walk b2381bc40b9ab8e1f010336e9cd9812579ebc8f4 # timeout=10

Prepending MATLAB to the PATH variable from this location: C:\Program Files\MATLAB\R2023b\bin

Generating MATLAB script with content:
buildtool

#################### Starting command output ####################
[myProject] $ C:\Users\hrastega\AppData\Local\Jenkins\.jenkins\workspace\myProject\.matlab\rWi2fRQn\run-matlab-command.exe '"setenv('MW_ORIG_WORKING_FOLDER', cd('C:\Users\hrastega\AppData\Local\Jenkins\.jenkins\workspace\myProject/.matlab/rWi2fRQn'));build_i6h8TEVM"' 
** Opened project 'Times Table App'

** Starting check
Analysis Summary:
    Total Files: 15
         Errors: 0 (Threshold: 0)
       Warnings: 3 (Threshold: Inf)
** Finished check

** Starting test
......

Test Summary:
    Total Tests: 6
         Passed: 6
         Failed: 0
     Incomplete: 0
       Duration: 0.41086 seconds testing time.
                 
** Finished test

** Starting archive
** Finished archive

** Closed project 'Times Table App'

Finished: SUCCESS

![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/48831250/9bcb8a72-5453-41d9-a2c5-46bbc2b52104)

**Comment by nbhoski** [comment] 2024-03-20 04:06
Hi @mw-hrastega which version of MATLAB are you using ? I did not see the sentinels printed in the log . I suspect the version which you are using does to have Davids changes. Coud you try with latest version

**Comment by Vahila** [comment] 2024-03-20 07:08
Hi Houman, I checked with the hpi generated from dev_main and 24a MATLAB, everything is working as expected at my end. Sharing the screenshots for reference.

![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/72e96f8c-489c-4a07-aa4c-4f34e07b6499)

![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/3df80cb0-3826-4192-a289-91ef7cf8f02c)

![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/5f48b060-fe77-47a4-bda9-0736b1a2f677)

**Comment by mw-hrastega** [comment] 2024-03-20 16:04
Hi, @Vahila and @nbhoski. Thanks for investigating. My Jenkins instance runs on my Windows machine and I used R2023b for my Jenkins build (the latest release). Are you saying that this feature is not supported in R2023b? 

Adding @davidbuzinski  to the thread.

**Comment by davidbuzinski** [comment] 2024-03-20 20:09
> Hi, @Vahila and @nbhoski. Thanks for investigating. My Jenkins instance runs on my Windows machine and I used R2023b for my Jenkins build (the latest release). Are you saying that this feature is not supported in R2023b?
> 
> Adding @davidbuzinski to the thread.

Hi @mw-hrastega

Support for this feature was added in all of the previous versions of MATLAB through an update version. Which update version of R2023b are you using? Can you try using the latest update?

Thanks,
David

**Comment by Vahila** [comment] 2024-03-21 04:23
> Hi, @Vahila and @nbhoski. Thanks for investigating. My Jenkins instance runs on my Windows machine and I used R2023b for my Jenkins build (the latest release). Are you saying that this feature is not supported in R2023b?
> 
> Adding @davidbuzinski to the thread.

Hi @mw-hrastega, the build visualization is supported from 22bU8, 23aU6, 23bU6. Can you try using 23b U6?

**Comment by mw-hrastega** [comment] 2024-03-21 14:27
> > Hi, @Vahila and @nbhoski. Thanks for investigating. My Jenkins instance runs on my Windows machine and I used R2023b for my Jenkins build (the latest release). Are you saying that this feature is not supported in R2023b?
> > Adding @davidbuzinski to the thread.
> 
> Hi @mw-hrastega
> 
> Support for this feature was added in all of the releases of MATLAB before R2024a through an update version. Which update version of R2023b are you using? Can you try using the latest update?
> 
> Thanks, David

Thanks for clarifying, David. I ended up using R2024a. However, I feel the behavior without an updated MATLAB release is still confusing. Could you work with @nbhoski to find a solution? For example, a better error message could have saved me.

**Comment by nbhoski** [comment] 2024-03-26 13:50
closing it as not a bug

**Closed by nbhoski** 2024-03-26 13:50 UTC
Labels: not bug
