### ISSUE TITLE
Not able to see code coverage report for folders added to the path

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/jenkins-matlab-plugin#169] opened 2020-11-17 22:25 UTC
Below is the pipeline script from https://github.com/mathworks/ci-test-repo. After running the pipeline I dont see the code coverage artifacts with files in "/Users/sjayagop/Desktop/src","/Users/sjayagop/Desktop/test"

pipeline {
   agent any
   environment {
      PATH="/Applications/MATLAB_R2019a.app:$PATH"
   }
   tools {
       matlab 'MATLABR2019a'
       matlab 'MATLABR2020b'
   }
 
    stages{
     
      
       stage('Run MATLAB Tests'){
            steps
            {
               runMATLABTests(
                               sourceFolder: ["/Users/sjayagop/Desktop/src","/Users/sjayagop/Desktop/test"],
                               testResultsTAP: 'new-results/results.tap',
                               testResultsJUnit: 'new-results/results.xml',
                               codeCoverageCobertura: 'new-coverage/coverage.xml',
                               modelCoverageCobertura: 'new-coverage/coverage.xml')
            }  
        }
    }        
    
}

**Comment by nbhoski** [comment] 2020-11-23 08:49
@SangaviJayagopi  is it that code coverage is not including the source files that you have provided against `sourceFolder`  ? 
@abhargav-mw  could you reproduce it locally ?

**Comment by abhargav-mw** [comment] 2020-12-01 05:26
@SangaviJayagopi can you include the generated test script from your console log?

**Comment by SangaviJayagopi** [comment] 2020-12-01 15:24
Genscript from console:

/Users/sjayagop/.jenkins/workspace/test_pipeline_source_folder/startup.m
Running MATLAB script with content:
import matlab.unittest.TestRunner;
import matlab.unittest.Verbosity;
import matlab.unittest.plugins.CodeCoveragePlugin;
import matlab.unittest.plugins.TAPPlugin;
import matlab.unittest.plugins.ToFile;
import matlab.unittest.plugins.XMLPlugin;
import matlab.unittest.plugins.codecoverage.CoberturaFormat;
import sltest.plugins.ModelCoveragePlugin;

addpath(genpath('/Users/sjayagop/Desktop/src'));
addpath(genpath('/Users/sjayagop/Desktop/test'));

suite = testsuite(pwd, 'IncludeSubfolders', true);

[~,~] = mkdir('new-coverage');
[~,~] = mkdir('new-results');

if exist(fullfile(pwd, 'new-results/results.tap'), 'file') == 2
    delete('new-results/results.tap');
end

runner = TestRunner.withTextOutput('OutputDetail', Verbosity.Detailed);
runner.addPlugin(TAPPlugin.producingVersion13(ToFile('new-results/results.tap')));
runner.addPlugin(XMLPlugin.producingJUnitFormat('new-results/results.xml'));
runner.addPlugin(CodeCoveragePlugin.forFolder({'/Users/sjayagop/Desktop/src', '/Users/sjayagop/Desktop/test'}, 'IncludingSubfolders', true, 'Producing', CoberturaFormat('new-coverage/coverage.xml')));
runner.addPlugin(ModelCoveragePlugin('Producing', CoberturaFormat('new-coverage/coverage.xml')));

results = runner.run(suite);

nfailed = nnz([results.Failed]);
assert(nfailed == 0, [num2str(nfailed) ' test(s) failed.']);

**Comment by SangaviJayagopi** [comment] 2020-12-01 15:30
The test mentioned in the pipeline script run but the code coverage report for them dont get generated.

Here is the error from Console log if it helps:

[Warning: The following error was caught while executing 'onCleanup' class destructor:
Error using matlab.unittest.internal.mustContainCharacters (line 13)
Invalid 'file' value. Input must contain one or more characters.

Error in matlab.unittest.internal.fileResolver (line 9)
mustContainCharacters(file,'file');

Error in matlab.unittest.internal.fileinformation.FileInformation.forFile (line 42)
            fullName = fileResolver(filename);

Error in matlab.unittest.internal.coverage.MATLABSource>getFileInformationFromFiles (line 27)
    fileInfoCell{idx} = FileInformation.forFile(files{idx});

Error in matlab.unittest.internal.coverage.MATLABSource/produceFileInformation (line 15)
                fileInfoCell{idx} = getFileInformationFromFiles(files);

Error in matlab.unittest.internal.services.coverage.MATLABCoberturaPublishingService/publish (line 17)
            fileInformationArray = theSources.produceFileInformation;

Error in matlab.unittest.internal.services.coverage.CoberturaPublishingService/fulfill (line 21)
                    services(serviceIndex).publish(fileName,sources,profileData);

Error in matlab.unittest.plugins.codecoverage.CoberturaFormat/generateCoverageReport (line 60)
           fulfill(coveragePublishingServices,coberturaFormat.Filename,sources,profileData);

Error in matlab.unittest.plugins.CodeCoveragePlugin/afterRun (line 271)
                format.generateCoverageReport(plugin.Sources,profileData);

Error in matlab.unittest.plugins.CodeCoveragePlugin>@()plugin.afterRun(pluginData) (line 279)
            finishup = onCleanup(@() plugin.afterRun(pluginData));

Error in onCleanup/delete (line 80)
            obj.task();

Error in matlab.unittest.plugins.CodeCoveragePlugin/runSession (line 281)
        end

Error in matlab.unittest.plugins.TestRunnerPlugin/invokeTestContentOperatorMethod_ (line 760)
                [varargout{1:nargout}] = method(plugin, pluginData);

Error in matlab.unittest.TestRunner/evaluateMethodOnPlugins (line 437)
            [varargout{1:nargout}] = iter.CurrentOperator.invokeTestContentOperatorMethod_(method, pluginData, iter);

Error in matlab.unittest.TestRunner/evaluateMethodOnPluginsFromMethodName (line 425)
            runner.evaluateMethodOnPlugins(str2func(method),pluginData);

Error in matlab.unittest.TestRunner/doRunWithFcn (line 408)
            runner.evaluateMethodOnPluginsFromMethodName(runFcn,pluginData);

Error in matlab.unittest.TestRunner/run (line 296)
            result = doRunWithFcn(runner,'runSession', pluginData);

Error in tempscript_0c4f (line 28)
results = runner.run(suite);

Error in scriptgen.Script/run (line 60)
                evalin('caller', strcat(scriptName, ';'));

Error in test_runner_dd0b6f38_e0d7_43b7_9a35_cc7a9119ac0c (line 6)
run(testScript);] 
[>In tempscript_0c4f (line 28)
In scriptgen/Script/run (line 60)
In test_runner_dd0b6f38_e0d7_43b7_9a35_cc7a9119ac0c (line 6)]
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS

**Comment by abhargav-mw** [comment] 2020-12-03 13:51
This seems to be an edge case with code coverage plugin in matlab unit test framework. I did find a related geck which is closed. I am closing this issue.

**Closed by abhargav-mw** 2020-12-03 13:51 UTC
Labels: question
