### ISSUE TITLE
Bul run action may not get added for the very first run

### ISSUE THREAD

**Issue by nbhoski** [mathworks/jenkins-matlab-plugin#341] opened 2024-07-05 06:17 UTC
the following will not add the build result window for the very first build run 

https://github.com/mathworks/jenkins-matlab-plugin/blob/7b7726060c1d629e5dbe84eee72b3df3810547aa/src/main/java/com/mathworks/ci/actions/RunMatlabBuildAction.java#L106

**Comment by sameagen-MW** [comment] 2024-07-08 15:20
Could you provide some more info here Nikhil? Is it related to changes on the dev branch, is it sporadic, what are you doing to produce the issue, etc...

That's the only interface that the `BuildArtifactAction` class exposes, and the line that you highlighted is identical to previous versions of the plugin. 

The difference would have to revolve around the handling of the `buildArtifact.json` file.

**Comment by sameagen-MW** [comment] 2024-07-08 17:10
Could you also check whether the issue is resolved in the branch for the linked pull request?

**Comment by Vahila** [comment] 2024-07-10 06:24
I tried the following:

- Update the 2.13.1 plugin version to hpi generated using the dev_main
- Created a Freestyle project with a build step
- I can see the table generated

**Comment by nbhoski** [comment] 2024-07-10 06:35
Thanks Vahila will close this

**Comment by nbhoski** [comment] 2024-07-10 06:35
Fixed

**Closed** 2024-07-10 06:35 UTC
Labels: bug
